# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc7443b1ef02bd3668e13c9265893e0ea8e8eb9f172531c29660d3fd070b5fe517db0c4d84ce6eaf119b12ec5c94574cde86e6707f7d841df94822ce86e54ea2

test:
  secret_key_base: a8ee080fe6155c34713648965df075b75abc8fc7f46d26bab3ac6af0a6bd1fa5e35ea5a547b88d4f57fb0cbeb2f91584c68050cd2d120cb4b4450a61b5c7bc21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
